apiVersion: v1
kind: Service     # S should be capital 
metadata: 
   name: redis
   labels:
     app: redis

spec:
  ports:
   - name: "redis-service"
     port: 6379
     targetPort: 6379 
  selector:
    app: redis
    