apiVersion: v1    # v should be capital in apiversion
kind: Pod         # p should be capital 
metadata:
  name: vote
  labels:
    app: vote 
spec: 
  containers:
   - name: vote
     image: dockersamples/examplevotingapp_vote
     ports: 
      - containerPort: 80    # p should be capital 
        name: vote